#####################################
###          Spring 配置          ###
#####################################
#Tomcat配置
server:
  servlet:
    context-path: /api
  port: 8090
  tomcat:
    uri-encoding: UTF-8

#日志配置
logging:
  config: classpath:config/logback-core.xml

#Spring配置
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    type: org.springframework.jdbc.datasource.DriverManagerDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jym?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true
    username: root
    password: 1qaz@WSX
  servlet:
    multipart:
      max-file-size: 100MB
    
#MyBatis配置
mybatis:
  config-location: classpath:config/SqlMapConfig.xml
  mapper-locations:
    - classpath:config/mysql/framework/*.xml
    - classpath:config/mysql/custom/*.xml

#Camunda配置
camunda:
  bpm:
    auto-deployment-enabled: true

#####################################
###            项目配置           ###
#####################################
core:
  #默认站点ID
  default-site-id: default
  #版本刷新时间(分)
  version-refresh-time: 10
  #系统管理员ID
  admin-id: admin
  #系统管理员密码
  admin-password: admin
  #系统管理员菜单ID
  admin-menu-id: _ADMIN
  #系统管理员ID
  update-login-date: true
  
  #DES加密盐值(8位)
  des-salt: uwelcome
  #每次批量插入处理的最大件数(0:无限制)
  batch-insert-max-count: 100
  #文件上传路径(file:C:\TEMP_PATH,classpath:TEMP_PATH,WEB-INF\TEMP_PATH)
  upload-path: file:C:\JYM_UPLOAD
  
  
  upload-type-path:
   #走马灯上传路径
   type3: file:F:\\suc\\ap\\ESS\\webclient\\ROOT_YJ\\static\\img
   type4: C:\jym_upload\
   type5:
   type6:
   type7:
   type8:
   type9:
  
  #OAuth2: 站点认证ClientID
  client-id-site: site
  #OAuth2: 站点认证ClientSecret
  client-secret-site: TF2HNC0TYG2ZARE45H89T
  #OAuth2: 手机认证ClientID
  client-id-mobile: mobile
  #OAuth2: 手机认证ClientSecret
  client-secret-mobile: S74125ERG28QA09YHNBDT
  #OAuth2: 企业微信认证ClientID
  client-id-qywx: qywx
  #OAuth2: 企业微信认证ClientSecret
  client-secret-qywx: TGBY7YHN89EDC4DFGT540
  #OAuth2: Windows认证ClientID
  client-id-spnego: spnego
  #OAuth2: Windows认证ClientSecret
  client-secret-spnego: ZTY2WSX7602TFCQYMVH56
  #OAuth2: Scope
  scope: scope
  #Token期限(分)
  token-timeout: 720
  
  #启用AD认证
  ad-authority: false
  #Spnego服务器地址
  spnego-url: 
  
  #启用企业微信认证
  qyapi-authority: false
  #企业微信:企业ID
  qyapi-corpid: 
  #企业微信:应用ID
  qyapi-agentid: 
  #企业微信:应用的凭证密钥
  qyapi-corpsecret: 
  #企业微信:商户号
  qyapi-mchid: 
  #企业微信:API证书地址
  qyapi-cert-path: 
  #企业微信:API密钥
  qyapi-key: 
  #外网地址
  api-server-url: 
  
  #启用钉钉认证
  ding-authority: false
  #钉钉:应用ID
  ding-appId: 
  #钉钉:应用案例码
  ding-appSecret: 

  #功能定义
  functions:
    P00: pageDataSearchProcess
    P01: pageDataInsertProcess
    P011: pageDataBatInsertProcess
    P02: pageDataUpdateProcess
    P021: pageDataUpdateByFKProcess
    P03: pageDataDeleteByPKProcess
    P04: pageDataDeleteByFKProcess
    P05: pageDataInsUpdProcess
    U00: userAddProcess
    U01: userUpdateProcess
    U02: userDeleteProcess
    U03: userUpdPasswordProcess
    B01: bpmnModelCreateProcess
    B02: bpmnModelUpdateProcess
    B03: bpmnModelDeleteProcess
    B04: bpmnModelDeployProcess
    B05: bpmnDeploySearchProcess
    B06: bpmnDeployDeleteProcess
    B12: applyInsertProcess
    B14: processDeleteProcess
    B17: approvalProcess
    B18: approvalAddUserProcess
    B20: processSignalProcess
    B35: processSearchProcess
    B36: taskSearchProcess
    B37: historicTaskSearchProcess
    #基于数据源的流程处理(废止)
    #B13: dsProcessSearchProcess
    #B15: dsApplyStatusProcess
    #B16: dsApprovalSearchProcess
    #B19: dsApprovalHistoryProcess
    #基于简单设定的流程处理
    B31: simpleApplyInsertProcess
    B32: simpleApplySearchProcess
    B33: simpleApplyVariableProcess
    B34: simpleTaskSearchProcess
    #存储过程调用
    C01: callProcedureProcess   
    
    I01: imageBase64Process
    I02: sendNoticeProcess
    I03: noticeRefreshProcess
    I04: resourceSaveProcess
    I05: resourceDeleteProcess
    I06: breakProcess
    I07: sqlSessionProcess
    
    #企业微信相关处理
    WX01: jsApiConfigProcess
    WX02: unifiedOrderProcess
    WX03: payRequestProcess
    WX04: refundProcess
    WX05: orderqueryProcess
    WX06: refundqueryProcess
    
    #交易猫商品平台外部商家权限包
    #交易猫外部商家批量发布商品
    JYM01: bacthPublishProcess
    JYM02: batchOnsaleProcess
    JYM03: batchOffsaleProcess
    JYM04: batchModifyPriceProcess
    JYM05: bacthTaskQProcess
    JYM06: statusBacthQProcess
    JYM11: createImageFolderProcess
    JYM12: createImageDataProcess
    JYM13: insertGoodsPropertyProcess
    JYM14: insertGoodsEntityProcess
    
jym:
  p1: 1642583217552236
  p2: 1642583217571262
  p3: 1642583217657360
  p4: 1642583217768016
  p5: 1642583217811076
  api_exec_enable: false
  local_netdisk_path: D:\testjym01
  netdisk_url: http://testjym01.pek3b.qingstor.com/
  access_key_id: KSFTUROANOPBWWQWEPWX
  secret_access_key: 18QiZVHqujjv7wRFWeztidxj78nGsUBidOeMrhRI
  bucketName: testjym01



